name: Auto add to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add ${{ github.event_name == 'issues' && 'Issue' || 'PR' }} to project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/add-to-project@v1.0.2
        continue-on-error: true
        with:
          project-url: https://github.com/orgs/sandec/projects/1
          github-token: ${{ secrets.PAT }}
